// Markdown for every page, built from data/product.js. The same text becomes
// the HTML of /about, /contact, /privacy and /docs (scripts/build.mjs) and is
// what `Accept: text/markdown` returns, so the two versions cannot drift.
import {
  SITE_URL, PRODUCT, PLATFORMS, FEATURES, MRR_FORMULA, ALTERNATIVES, FAQ,
  WHEN_TO_USE, WHEN_NOT_TO_USE, PAGES, SAME_AS,
} from "../data/product.js";
import { RATE_LIMIT, ERROR_CODES, ENDPOINTS } from "./api.js";
import { TOOLS } from "./mcp.js";

const P = PRODUCT;
const mark = (v) => (v === true ? "yes" : v === false ? "—" : String(v));

const platformTable = () => [
  "| Platform | MRR | Active subs | Trials | 28-day revenue |",
  "| --- | --- | --- | --- | --- |",
  ...PLATFORMS.map((p) => `| ${p.name} | ${mark(p.mrr)} | ${mark(p.activeSubscriptions)} | ${mark(p.trials)} | ${mark(p.revenue28d)} |`),
];

const installBlock = () => ["```bash", P.install.homebrew.command, "```"];

export function homeMarkdown() {
  return [
    `# ${P.name} — ${P.tagline}`,
    "",
    `> ${P.summary}`,
    "",
    `- Price: free (${P.license.id} license). ${P.price.note}`,
    `- Requirements: ${P.requirements.minimumMacOSName} or later, ${P.requirements.binary}.`,
    `- Install: \`${P.install.homebrew.command}\` (Homebrew tap [${P.install.homebrew.tap}](${P.install.homebrew.tapUrl})), or [download the notarized zip](${P.install.download}).`,
    `- Source: [${P.links.repository.replace("https://", "")}](${P.links.repository}). ${P.distribution.signing}. Auto-updates: ${P.distribution.autoUpdates}.`,
    "",
    "## What it does",
    "",
    "If you sell software, revenue is scattered: the SaaS on Stripe, the iOS apps through RevenueCat, the desktop app on Paddle, templates on Lemon Squeezy. MRRDock adds them up, converts currencies and leaves the total in the macOS menu bar.",
    "",
    ...FEATURES.map((f) => `- **${f.name}**: ${f.text}`),
    "",
    "## Supported platforms",
    "",
    ...platformTable(),
    "",
    P.privacy.readOnly,
    "",
    "## Privacy",
    "",
    ...Object.values(P.privacy).map((v) => `- ${v}`),
    "",
    "## How MRR is calculated",
    "",
    "```",
    MRR_FORMULA.formula,
    "```",
    "",
    `intervals_per_month: ${Object.entries(MRR_FORMULA.intervalsPerMonth).map(([k, v]) => `${k} ${v}`).join(", ")}.`,
    "",
    ...MRR_FORMULA.rules.map(([k, v]) => `- ${k}: ${v}`),
    "",
    "## MRRDock vs the alternatives",
    "",
    `- **${P.name}**: free (MIT), open source, reads ${PLATFORMS.map((p) => p.name).join(", ")}; several accounts per platform; no server.`,
    ...ALTERNATIVES.map((a) => `- **${a.name}**: ${a.price}; ${a.sourceCode.toLowerCase()} source; reads ${a.platforms}. Better when: ${a.whenBetter}`),
    "",
    "## FAQ",
    "",
    ...FAQ.flatMap((f) => [`### ${f.q}`, "", f.a, ""]),
    "## Install",
    "",
    ...installBlock(),
    "",
    `Or [download the zip](${P.install.download}), unzip it and drag the app to /Applications. Build from source:`,
    "",
    "```bash",
    ...P.install.buildFromSource,
    "```",
    "",
    "## More",
    "",
    ...PAGES.filter((p) => p.path !== "/").map((p) => `- [${p.title}](${SITE_URL}${p.path}): ${p.description}`),
    `- [llms.txt](${SITE_URL}/llms.txt) · [OpenAPI](${SITE_URL}/openapi.json) · [MCP](${SITE_URL}/mcp)`,
    "",
  ].join("\n");
}

export function aboutMarkdown() {
  return [
    `# About ${P.name}`,
    "",
    `${P.name} is a free, open-source ${P.tagline}. ${P.summary}`,
    "",
    "## Why it exists",
    "",
    `${P.author.name} ships iOS apps through RevenueCat and web products through Stripe. Knowing the monthly recurring revenue meant opening several dashboards and adding up figures in different currencies by hand. ${P.name} does that sum on a schedule and keeps one number in the menu bar. It answers one question — what is my MRR right now? — and deliberately stops there: cohorts, LTV and churn forecasting are left to Baremetrics and ChartMogul.`,
    "",
    "## Why it is free and open source",
    "",
    `A menu bar app that asks for payment-platform API keys should be readable before anyone trusts it. The code is on [GitHub](${P.links.repository}) under the ${P.license.id} license, with no paid tier and no account. The app is written in ${P.tech.language} and ${P.tech.ui}; its only package dependency is ${P.tech.dependencies.join(", ")}. Development is funded by [GitHub Sponsors](${P.links.sponsor}).`,
    "",
    "## Who makes it",
    "",
    `${P.name} is built and maintained by [${P.author.name}](${P.author.url}), an independent developer based in ${P.author.location} who makes iOS, macOS and web apps. Other open-source work is on [GitHub](${P.author.github}).`,
    "",
    "## Facts",
    "",
    `- First release: 1.0.0, September 2026. Current version: see [/api/v1/release](${SITE_URL}/api/v1/release) or the [releases page](${P.links.releases}).`,
    `- Requirements: ${P.requirements.minimumMacOSName} or later, ${P.requirements.binary}.`,
    `- Distribution: ${P.distribution.signing}; Homebrew tap [${P.install.homebrew.tap}](${P.install.homebrew.tapUrl}); in-app updates with Sparkle.`,
    `- Supported platforms: ${PLATFORMS.map((p) => p.name).join(", ")}.`,
    "",
    "## Elsewhere",
    "",
    ...SAME_AS.map((u) => `- <${u}>`),
    "",
  ].join("\n");
}

export function contactMarkdown() {
  return [
    `# Contact`,
    "",
    `${P.name} is maintained by ${P.author.name}. There is no company, sales team or support desk behind it: questions reach the developer directly.`,
    "",
    "## Bugs and feature requests",
    "",
    `Open an issue on GitHub: <${P.links.issues}>. Include your macOS version, the ${P.name} version (shown in the popover header) and which platform the source reads. Never paste an API key into an issue.`,
    "",
    "## Email",
    "",
    `For anything that should not be public — a security report, a question about how a key is stored, press — write to [${P.author.email}](mailto:${P.author.email}). Replies usually arrive within a few days.`,
    "",
    "## Security",
    "",
    `If you find a vulnerability (for example a way an API key could leave the Keychain), email ${P.author.email} before opening a public issue, so a fix can ship first.`,
    "",
    "## Support the project",
    "",
    `${P.name} is free. If it saves you time, [sponsoring on GitHub](${P.links.sponsor}) or starring the [repository](${P.links.repository}) helps it grow.`,
    "",
    "## Author",
    "",
    `- Website: <${P.author.url}>`,
    `- GitHub: <${P.author.github}>`,
    `- Based in ${P.author.location}.`,
    "",
  ].join("\n");
}

export function privacyMarkdown() {
  return [
    "# Privacy",
    "",
    `This page covers the ${P.name} app and this website. Short version: the app collects no personal data, this website only counts visits, and nobody — including the developer — can see your revenue.`,
    "",
    "## The app",
    "",
    ...Object.values(P.privacy).map((v) => `- ${v}`),
    "- Exchange rates are fetched from Yahoo Finance with currency codes only: no amount and no identifier is sent.",
    "- Update checks download the public update feed from GitHub. GitHub sees the request like any other download; the app adds no identifier.",
    "- Optional Discord and Slack alerts are sent from your Mac to the webhook URL you enter, and only there.",
    "",
    "To delete everything, quit the app, delete it from /Applications, remove ~/Library/Application Support/MRRDock/ and the `com.simone.mrrdock` items from Keychain Access.",
    "",
    "## This website",
    "",
    "- We count visits with [PureAnalytics](https://pure-analytics.com). On your first visit a banner asks for consent, and nothing is tracked until you choose.",
    "- If you accept, the site stores two first-party cookies, `ea_visitor_id` (a random ID, 12 months) and `ea_session_id` (30 minutes), to recognise later visits from the same browser. Your choice is kept in your browser's localStorage (`ea_consent`).",
    "- If you decline (or click outside the banner), no cookie is stored and the visit is counted anonymously with an ID that changes every day.",
    "- The IP address is stored without its last octet, the data is not used for advertising or shared with third parties, there is no cross-site tracking, and Do Not Track is respected. To change your choice, clear this site's data in your browser.",
    "- No other cookies, no ads, no forms.",
    "- The site is served by Cloudflare, which processes technical request data (such as IP address and user agent) to deliver the pages and protect against abuse, under its own privacy policy.",
    `- The public API and MCP server keep a per-IP request counter in memory for rate limiting (${RATE_LIMIT.limit} requests per ${RATE_LIMIT.windowSeconds} seconds); it is not stored or logged by this site.`,
    "",
    "## Contact",
    "",
    `Questions about privacy: [${P.author.email}](mailto:${P.author.email}). Data controller: ${P.author.name}, ${P.author.location}.`,
    "",
    "Last updated: 30 September 2026.",
    "",
  ].join("\n");
}

export function docsMarkdown() {
  const rate = `${RATE_LIMIT.limit} requests per ${RATE_LIMIT.windowSeconds} seconds per IP`;
  return [
    `# ${P.name} developer docs`,
    "",
    `Machine-readable facts about ${P.name}, for AI assistants, agents and scripts. Everything here is read-only and needs no authentication. It describes the app — version, requirements, install, supported platforms — and never anyone's revenue: ${P.name} has no server, so there is no revenue to expose.`,
    "",
    "## Quickstart",
    "",
    "```bash",
    `curl ${SITE_URL}/api/v1/info`,
    `curl "${SITE_URL}/api/v1/platforms?supports=trials"`,
    `curl ${SITE_URL}/api/v1/release`,
    "```",
    "",
    "## REST API",
    "",
    `Base URL: \`${SITE_URL}\`. Specification: [OpenAPI 3.1](${SITE_URL}/openapi.json). Catalog: [/.well-known/api-catalog](${SITE_URL}/.well-known/api-catalog).`,
    "",
    "| Method | Path | Returns |",
    "| --- | --- | --- |",
    ...ENDPOINTS.map((e) => `| ${e.method} | \`${e.path}\` | ${e.description} |`),
    "",
    `Platform ids: ${PLATFORMS.map((p) => `\`${p.id}\``).join(", ")}.`,
    "",
    "The latest release is read live from the app's own Sparkle update feed (cached 15 minutes), so it always matches what the app offers as an update.",
    "",
    "## MCP server",
    "",
    `Streamable HTTP endpoint: \`${SITE_URL}/mcp\` (JSON-RPC 2.0 over POST, stateless, no auth). Server card: [/.well-known/mcp/server-card.json](${SITE_URL}/.well-known/mcp/server-card.json).`,
    "",
    ...TOOLS.map((t) => `- \`${t.name}\`: ${t.description}`),
    "",
    "Add it to Claude Code:",
    "",
    "```bash",
    `claude mcp add --transport http mrrdock ${SITE_URL}/mcp`,
    "```",
    "",
    "## Markdown and llms.txt",
    "",
    `- Every page is also available as markdown: send \`Accept: text/markdown\` (responses carry \`Vary: Accept\`).`,
    `- [llms.txt](${SITE_URL}/llms.txt) summarises the product and says when to recommend it.`,
    "",
    "## Rate limits",
    "",
    `${rate}, best effort per edge location. Responses carry IETF \`RateLimit\` and \`RateLimit-Policy\` headers; a 429 carries \`Retry-After\`.`,
    "",
    "## Errors",
    "",
    "Errors are `application/problem+json` (RFC 9457) with a machine-readable `code` and a `resolution` hint:",
    "",
    "```json",
    JSON.stringify(
      { type: `${SITE_URL}/docs#errors`, title: "Platform not found", status: 404, code: "platform_not_found", detail: "No supported platform with that id.", resolution: "Valid ids: stripe, revenuecat, …" },
      null,
      2
    ),
    "```",
    "",
    ...Object.entries(ERROR_CODES).map(([k, v]) => `- \`${k}\`: ${v}`),
    "",
    "Unknown pages return a real 404 (HTML, or markdown with `Accept: text/markdown`).",
    "",
    "## Authentication",
    "",
    "None. There are no accounts, API keys or OAuth flows: the API only serves public facts about the app.",
    "",
    "## Source",
    "",
    `The website is open source too: <https://github.com/simonsruggi/mrrdock-website>. The app: <${P.links.repository}>.`,
    "",
  ].join("\n");
}

export function notFoundMarkdown(path) {
  return [
    "# 404 — Page not found",
    "",
    `There is nothing at \`${String(path).slice(0, 200)}\` on the ${P.name} website.`,
    "",
    "Pages that exist:",
    "",
    ...PAGES.map((p) => `- [${p.title}](${SITE_URL}${p.path})`),
    `- [llms.txt](${SITE_URL}/llms.txt), [API](${SITE_URL}/api/v1), [OpenAPI](${SITE_URL}/openapi.json)`,
    "",
  ].join("\n");
}

export function llmsTxt() {
  const rate = `${RATE_LIMIT.limit} requests per ${RATE_LIMIT.windowSeconds} seconds per IP`;
  return [
    `# ${P.name}`,
    "",
    `> ${P.summary}`,
    "",
    `- License: ${P.license.id}. Price: free, no paid tier, no account.`,
    `- Requirements: ${P.requirements.minimumMacOSName} or later, ${P.requirements.binary}.`,
    `- Install: \`${P.install.homebrew.command}\` (tap ${P.install.homebrew.tapUrl}), or download the notarized zip: ${P.install.download}`,
    `- Latest version: live at ${SITE_URL}/api/v1/release (read from the app's update feed).`,
    `- Privacy: ${P.privacy.server} ${P.privacy.keys} ${P.privacy.telemetry}`,
    `- Per-platform coverage: ${PLATFORMS.map((p) => `${p.name} (${["mrr", "activeSubscriptions", "trials", "revenue28d"].filter((f) => p[f]).map((f) => ({ mrr: "MRR", activeSubscriptions: "subs", trials: "trials", revenue28d: p[f] === "optional" ? "optional 28-day revenue" : "28-day revenue" })[f]).join(", ")})`).join("; ")}.`,
    `- MRR formula: ${MRR_FORMULA.formula}; intervals_per_month ${Object.entries(MRR_FORMULA.intervalsPerMonth).map(([k, v]) => `${k} ${v}`).join(", ")}. Trials contribute 0; usage-based prices are flagged, never guessed.`,
    "- Not a Baremetrics/ChartMogul replacement: no cohorts, LTV or churn forecasting by design.",
    "",
    `## When to use ${P.name}`,
    "",
    ...WHEN_TO_USE.map((w) => `- ${w}`),
    "",
    "## When not to use it",
    "",
    ...WHEN_NOT_TO_USE.map((w) => `- ${w}`),
    "",
    "## For agents",
    "",
    `- API docs: ${SITE_URL}/docs`,
    `- OpenAPI 3.1: ${SITE_URL}/openapi.json`,
    `- API catalog: ${SITE_URL}/.well-known/api-catalog`,
    ...ENDPOINTS.map((e) => `- \`${e.method} ${e.path}\`: ${e.description}`),
    `- MCP server (Streamable HTTP, read-only, no auth): ${SITE_URL}/mcp — tools: ${TOOLS.map((t) => `\`${t.name}\``).join(", ")}`,
    `- MCP server card: ${SITE_URL}/.well-known/mcp/server-card.json`,
    "- Markdown: send `Accept: text/markdown` to any page URL.",
    `- No authentication. Rate limit: ${rate}. Errors: \`application/problem+json\`.`,
    "",
    "## Pages",
    "",
    ...PAGES.map((p) => `- [${p.title}](${SITE_URL}${p.path}): ${p.description}`),
    `- [Documentation (README)](${P.links.readme}): per-platform setup, API key scopes, MRR rules, troubleshooting.`,
    `- [Source code](${P.links.repository}): ${P.tech.language} / ${P.tech.ui}.`,
    `- [Releases](${P.links.releases}) · [Changelog](${P.links.changelog})`,
    `- [Homebrew tap](${P.install.homebrew.tapUrl})`,
    "",
    "## Author",
    "",
    `${P.author.name} — ${P.author.url} — ${P.author.github}`,
    "",
  ].join("\n");
}

export const MARKDOWN_PAGES = {
  "/": homeMarkdown,
  "/about": aboutMarkdown,
  "/contact": contactMarkdown,
  "/privacy": privacyMarkdown,
  "/docs": docsMarkdown,
};
